.class public final Lcom/samsung/android/sdk/ssf/message/io/SSMGPB;
.super Ljava/lang/Object;


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$SaveCallLogReply;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$SaveCallLogRequest;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ChangeActiveConnectionReply;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ChangeActiveConnectionRequest;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ConnectionReset;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$CloseGatewayReply;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$CloseGatewayRequest;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$OpenGatewayReply;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$OpenGatewayRequest;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$NotificationReply;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$NotificationRequest;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$AlternativePushReply;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$AlternativePushRequest;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$UnsealMessageReply;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$UnsealMessageRequest;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$RefreshGroupKeyReply;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$RefreshGroupKeyRequest;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$AcceptInvitationReply;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$AcceptInvitation;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$DestroyChatroomReply;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$DestroyChatroomRequest;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$RecallMessageReply;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$RecallMessageRequest;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$TypingUpdated;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$IsTyping;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$UnsubscribeTypingStatusReply;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$UnsubscribeTypingStatus;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$SubscribeTypingStatusReply;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$SubscribeTypingStatus;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ChangeChatroomMetaReply;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ChangeChatroomMetaRequest;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ChangeOwnerReply;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ChangeOwnerRequest;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$RemoveMemberReply;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$RemoveMemberRequest;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$InviteReply;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$InviteRequest;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$EndChatReply;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$EndChatRequest;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ReadMessageReply;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ReadMessageRequest;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ForwardUnreadMessageReply;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ForwardUnreadMessage;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ForwardOnlineMessageReply;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ForwardOnlineMessage;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$GetAllUnreadMessageReply;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$GetAllUnreadMessageRequest;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$AllowChatReply;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$AllowChatRequest;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ChatReply;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ChatRequest;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$CreateChatroomReply;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$CreateChatroomRequest;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$CurrentTimeReply;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$CurrentTimeRequest;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ServerEchoReply;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ServerEcho;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ClientEchoReply;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ClientEcho;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ChannelAuthReply;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ChannelAuthRequest;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$GroupKeyEntry;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$EndChatEntry;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ChatroomMemberStatus;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$SecureChatDevice;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$WaterMarkEntry;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ProcessedMessageEntry;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ChatMessageParam;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$InboxEntry;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$Result;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$WrongReceiverDetail;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$DIDViolationUser;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$SaveCallLogReplyOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$SaveCallLogRequestOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ChangeActiveConnectionReplyOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ChangeActiveConnectionRequestOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ConnectionResetOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$CloseGatewayReplyOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$CloseGatewayRequestOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$OpenGatewayReplyOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$OpenGatewayRequestOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$NotificationReplyOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$NotificationRequestOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$AlternativePushReplyOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$AlternativePushRequestOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$UnsealMessageReplyOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$UnsealMessageRequestOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$RefreshGroupKeyReplyOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$RefreshGroupKeyRequestOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$AcceptInvitationReplyOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$AcceptInvitationOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$DestroyChatroomReplyOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$DestroyChatroomRequestOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$RecallMessageReplyOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$RecallMessageRequestOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$TypingUpdatedOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$IsTypingOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$UnsubscribeTypingStatusReplyOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$UnsubscribeTypingStatusOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$SubscribeTypingStatusReplyOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$SubscribeTypingStatusOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ChangeChatroomMetaReplyOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ChangeChatroomMetaRequestOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ChangeOwnerReplyOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ChangeOwnerRequestOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$RemoveMemberReplyOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$RemoveMemberRequestOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$InviteReplyOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$InviteRequestOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$EndChatReplyOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$EndChatRequestOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ReadMessageReplyOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ReadMessageRequestOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ForwardUnreadMessageReplyOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ForwardUnreadMessageOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ForwardOnlineMessageReplyOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ForwardOnlineMessageOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$GetAllUnreadMessageReplyOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$GetAllUnreadMessageRequestOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$AllowChatReplyOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$AllowChatRequestOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ChatReplyOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ChatRequestOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$CreateChatroomReplyOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$CreateChatroomRequestOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$CurrentTimeReplyOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$CurrentTimeRequestOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ServerEchoReplyOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ServerEchoOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ClientEchoReplyOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ClientEchoOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ChannelAuthReplyOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ChannelAuthRequestOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$GroupKeyEntryOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$EndChatEntryOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ChatroomMemberStatusOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$SecureChatDeviceOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$WaterMarkEntryOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ProcessedMessageEntryOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ChatMessageParamOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$InboxEntryOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ResultOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$WrongReceiverDetailOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$DIDViolationUserOrBuilder;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ConnectionResetCause;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$IsTypingContentType;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$NotiType;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$MsgType;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ChatType;,
        Lcom/samsung/android/sdk/ssf/message/io/SSMGPB$ProxyOption;
    }
.end annotation


# direct methods
.method static constructor <clinit>()V
    .locals 0

    return-void
.end method

.method private constructor <init>()V
    .locals 0

    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method

.method public static registerAllExtensions(Lcom/google/protobuf/ExtensionRegistryLite;)V
    .locals 0

    return-void
.end method
